# Generated by Django 4.2.23 on 2026-06-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureDataM1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capteur_Id', models.CharField(max_length=32)),
                ('piece', models.CharField(max_length=80)),
                ('date', models.CharField(max_length=20)),
                ('heure', models.CharField(max_length=20)),
                ('temp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureDataM2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capteur_Id', models.CharField(max_length=32)),
                ('piece', models.CharField(max_length=80)),
                ('date', models.CharField(max_length=20)),
                ('heure', models.CharField(max_length=20)),
                ('temp', models.FloatField()),
            ],
        ),
    ]
