# Generated by Django 4.2.23 on 2026-06-22 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('piece', models.CharField(max_length=50)),
                ('emplacement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MesureMaison2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saeapp.capteur')),
            ],
        ),
        migrations.CreateModel(
            name='MesureMaison1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saeapp.capteur')),
            ],
        ),
    ]
